language: csharp

mono: none
dotnet: 2.1

sudo: false

script:
  - cd HatsushimoTest; dotnet test; cd ..
  - cd MikazukiTest; dotnet build; cd ..

branches:
  only:
    - master

notifications:
  email: false
