language: csharp

mono: none
dotnet: 2.1

sudo: false

script:
  # shared lib
  - cd HatsushimoTest; dotnet test; cd ..
  
  # server
  - cd MikazukiTest; dotnet test; cd ..
  - cd MikazukiRunner; dotnet build; cd ..
  
  # bot
  - cd ShigureRunner; dotnet build; cd ..

branches:
  only:
    - master

notifications:
  email: false
